from ....params import BOOLEAN, ISABMode, LoRAMode, OPTIMS, ACTIVATIONS, LOSSES, SOFTMAXES, GRADIENT_PENALTY_MODES, PMAFFNMode, CombineMode, IndsInitMode
from torch import nn, optim
from torch.nn import functional as F

DEFAULTS = {
    "Body": "twin_encoder",
    "loss_balancer_meta": True,
    "loss_balancer_log": False,
    "loss_balancer_lbtw": False,
    "pma_skip_small": False, #for now, don't skip
    "isab_skip_small": False, #for now, don't skip
    "layer_norm": False,
    "pma_layer_norm": False,
    "attn_residual": True,
    "tf_n_layers_dec": False, 
    "tf_isab_rank": 0,
    "tf_lora": False,
    "tf_layer_norm": False,
    "tf_pma_start": -1,
    "ada_n_seeds": 0,
    "head_n_seeds": 0,
    "tf_pma_low": 1,
    "gradient_penalty_kwargs": {
        "mag_loss": True,
        "mse_mag": True,
        "mag_corr": False,
        "seq_mag": False,
        "cos_loss": False,
        "mse_mag_kwargs": {
            "target": 0.0,
            "multiply": False,
        },
        "mag_corr_kwargs": {
            "only_sign": False,
        },
        "cos_loss_kwargs": {
            "only_sign": True,
            "cos_matrix": False,
        },
    },
    "dropout": 0,
    "combine_mode": CombineMode.DIFF_LEFT,
    "tf_isab_mode": ISABMode.SEPARATE,
    "grad_loss_fn": "mse",
}

PARAM_SPACE = {
    **DEFAULTS,
    # Dataset args
    "dataset_size": ("int_exp_2", 32, 2048),
    "batch_size": ("int_exp_2", 2, 4),
    # Training args
    "epochs": ("log_int", 500, 700),
    #"lr": ("log_float", 5e-3, 1e-2),
    "lr_mul": ("log_float", 0.09, 0.2),
    "n_warmup_steps": ("log_float", 35, 100),
    "Optim": ("optimizer", [
        # #"adamw", 
        #"sgdmomentum", 
        "amsgradw",
        # ##"adadelta",
        #"padam", 
        #"nadam",
        #"adabound",
        # ##"adahessian",
        "adamp",
        "diffgrad",
        # "qhadam",
        # #"yogi",
    ]),
    # Training args
    "non_role_model_mul": ("float", 1.0, 2.0),
    #"non_role_model_avg": BOOLEAN,
    #"non_role_model_avg": True, 
    #"std_loss_mul": ("float", 0.5, 2.0),
    #"grad_loss_mul": ("float", 0.7, 1.0),
    "loss_balancer_meta": ("conditional", {
        "loss_balancer_beta": ("float", 0.65, 0.98),
        "loss_balancer_r": ("float", 0.9, 0.95),
    }),
    #"loss_balancer_log": BOOLEAN, #True
    #"loss_balancer_lbtw": BOOLEAN, #True
    #"grad_loss_mul": ("float", 0.3, 1),
    #"loss_fn": ("loss", "mse"),
    "grad_loss_fn": ("loss", "mse"),
    #"std_loss_fn": ("loss", ["mean_penalty_log_half"]),
    # "grad_loss_fn": ("loss", [
    #     #"mse", 
    #     "mae", 
    #     "huber", 
    #     "mile", 
    #     "mire"
    # ]),
    "adapter_loss_fn": ("loss", [
        "mse", 
        # "mae", 
        # "huber", 
        "mile", 
        "mire",
    ]),
    "fixed_role_model": ("categorical", [
        #None, 
        #"tvae", 
        "tvae", 
        #"lct_gan_latent", 
        #"tab_ddpm_concat", 
        #"realtabformer",
        #"realtabformer_latent",
    ]),
    "gradient_penalty_mode": ("gradient_penalty_mode", [
        "NONE", # for now, let's not grad penalty
        # "ALL", # ALL was the best, but it takes a long time to train
        # "ONCE",
        # "ESTIMATE",
        # #"AVERAGE_NO_MUL",
        # "AVERAGE_MUL"
    ]),
    # "g_loss_mul": ("log_float", 1e-5, 0.1),
    # "non_role_model_mul": ("log_float", 1e-5, 1.0),
    # "mse_mag": ("conditional", {
    #     "mse_mag": True,
    #     "mse_mag_target": ("log_float", 0.005, 1.0),
    # }),
    # #"mag_corr": ("conditional", {
    # "mag_corr": True,
    # "mag_corr_target": ("log_float", 0.01, 0.1),
    # "mag_corr_only_sign": False,
    # "mag_corr_sign": BOOLEAN,
    # #}),
    # "cos_loss": ("conditional", {
    #     "cos_loss": True,
    #     "cos_loss_target": ("log_float", 0.003, 0.62),
    #     "cos_loss_only_sign": True,
    # }),
    # Common model args
    "d_model": ("int_exp_2", 128, 128), 
    "dropout": ("bool_float", 0.15, 0.5), 
    #"dropout": ("float", 0.15, 0.15), #close to random
    #"softmax": ("softmax", "relu15"),
    #"flip": False,
    #"pma_skip_small": BOOLEAN,
    #"isab_skip_small": BOOLEAN,
    #"skip_small": False,
    #"loss_clamp": ("log_float", 0.6, 1.0), #almost random
    "grad_clip": ("log_float", 0.25, 1.0),
    "bias": BOOLEAN,
    #"bias": False,
    "bias_final": BOOLEAN,
    #"pma_layer_norm": BOOLEAN,
    "attn_activation": ("activation", [
        #"tanh",  
        # # #"sigmoid", 
        # "relu",
        # "leakyrelu", 
        #"selu",
        # # #"prelu",
        # # "rrelu",
        # # #"relu6",
        # #"hardtanh",
        # # #"hardsigmoid",
        # # "softsign",
        # # #"identity",
        "leakyhardtanh",
        "leakyhardsigmoid",
    ]),
    #"attn_residual": BOOLEAN,
    "inds_init_mode": ("categorical", [
        IndsInitMode.TORCH,
        #IndsInitMode.FIXNORM,
        IndsInitMode.XAVIER,
    ]),
    # Transformer args
    "tf_d_inner": ("int_exp_2", 256, 256),
    "tf_n_layers_enc": ("int", 4, 4), 
    #"tf_n_layers_dec": ("bool_int", 2, 3), #better false
    "tf_n_head": ("int_exp_2", 16, 16), 
    "tf_activation": ("activation", [
        #"tanh", 
        # # #"sigmoid",
        # "relu", 
        # "leakyrelu", 
        #"selu",
        # "prelu",
        # # "rrelu",
        # "relu6",
        # # #hardtanh",
        # #"hardsigmoid",
        # # #"softsign",
        "leakyhardtanh",
        #"leakyhardsigmoid",
    ]),
    "tf_activation_final": ("activation", [
        #"leakyhardtanh",
        "leakyhardsigmoid",
    ]),
    #"tf_num_inds": ("bool_int_exp_2", 16, 128),
    #"tf_num_inds": ("conditional", {
    "tf_num_inds": ("int_exp_2", 64, 64),
    "tf_isab_mode": ("categorical", (
        ISABMode.SEPARATE, 
        #ISABMode.SHARED,
        #ISABMode.MINI,
    )),
    #}),
    # "tf_isab_rank": ("bool_int_exp_2", 1, 32), #doesn't matter so true it is
    # "tf_lora": ("conditional", {
    #     "tf_lora_mode": ("categorical", (
    #         #LoRAMode.LOW_RANK, 
    #         LoRAMode.LORA,
    #     )),
    #     "tf_lora_rank": ("int_exp_2", 2, 32), #Mustn't be bool int
    # }),
    #"tf_layer_norm": BOOLEAN,
    # "combine_mode": ("categorical", [
    #     CombineMode.CONCAT,
    #     CombineMode.DIFF_LEFT,
    #     #CombineMode.DIFF_RIGHT,
    #     #CombineMode.MEAN,
    #     #CombineMode.PROD
    # ]),
    # Transformer PMA args
    #"tf_pma": ("conditional", { #better true
    #"tf_pma_start": ("int", -2, -1),
    "tf_pma_low": ("int_exp_2", 2, 4),
    #"tf_pma_high": ("int_exp_2", 4, 8),
    # "tf_pma_rank": ("bool_int_exp_2", 2, 32), #true better
    # #}),
    # "pma_ffn_mode": ("categorical", (
    #     PMAFFNMode.NONE,
    #     PMAFFNMode.SEPARATE,
    #     PMAFFNMode.SHARED,
    # )),
    #"tf_share_ffn": BOOLEAN, 
    #"tf_share_ffn": True,
    # Adapter args
    # "ada_n_seeds": ("conditional", {
    #     "ada_n_seeds": ("int_exp_2", 1, 2),
    #     "ada_n_head": ("int_exp_2", 4, 32),
    # }),
    "ada_d_hid": ("int_exp_2", 512, 512), 
    "ada_n_layers": ("int", 6, 6), 
    "ada_activation": ("activation", [
        #"tanh",  
        # #"sigmoid", 
        #"relu",
        # #"leakyrelu", 
        #"selu",
        # "prelu",
        # #"rrelu",
        #"relu6",
        # #"hardtanh",
        # #"hardsigmoid",
        #"softsign",
        #"leakyhardtanh",
        "leakyhardsigmoid",
    ]),
    "ada_activation_final": ("activation", [
        # # "tanh", 
        # "sigmoid", 
        # "relu6",
        # #"hardtanh",
        # # #"hardsigmoid",
        # "softsign",
        # "identity",
        "leakyhardtanh",
        #"leakyhardsigmoid",
    ]),
    # Head args
    "head_d_hid": ("int_exp_2", 128, 128), 
    "head_n_layers": ("int", 6, 7), 
    "head_n_head": ("int_exp_2", 32, 32),
    "head_activation": ("activation", [
        "tanh",  
        # # #"sigmoid", 
        # # #"relu",
        # # "leakyrelu", 
        #"selu", 
        # "prelu",
        # "rrelu",
        # # "relu6",
        # #"hardtanh",
        # # #"hardsigmoid",
        # "softsign",
        #"leakyhardtanh",
        #"leakyhardsigmoid",
    ]),
    "head_activation_final": ("activation", [
        # #"sigmoid", 
        # "tanh",
        # #"hardtanh",
        # "softsign",
        # #"logsigmoid",
        "identity",
        #"leakyhardtanh",
    ]),
    #"head_final_mul": ("categorical", [
    #    "identity",
    #    "minus",
    #    "oneminus",
    #    "oneplus",
    #]),
    "patience": ("log_int", 75, 100),
}

PARAM_SPACE_2 = {
    #"dataset_size_low": ("int_exp_2", 2048, 2048),
    #"dataset_size_high": ("int_exp_2", 2048, 2048),
    "dataset_size_low": ("int_exp_2", 1024, 1024),
    "dataset_size_high": ("int_exp_2", 1024, 2048), # param must exist
    "batch_size_low": ("int_exp_2", 4, 4),
    "batch_size_high": ("int_exp_2", 4, 4),
    "scheduler_patience": ("log_int", 10, 30),
}

#GOOD = [22, 24, 25, 26, 27, 28, 35, 36, 37, 46, 51, 53]
#GOOD = [24, 25, 26, 35, 53]
#GOOD = [1, 2, 3, 6, 11]
GOOD = [0, 1, 2, 3, 4]
#[0.0013133894972270355, 0.00498013350685748]
BEST = {
    **DEFAULTS,
    'loss_balancer_meta_boolc': True,
    'loss_balancer_beta': 0.8343821358126027,
    'loss_balancer_r': 0.9160900273227203,
    'tf_pma_low_exp_2': 1,
    'epochs': 541,
    'lr_mul': 0.08945880792103897,
    'n_warmup_steps': 45.24766063142192,
    'Optim': 'adamp',
    'non_role_model_mul': 1.823668051278738,
    'adapter_loss_fn': 'mse',
    'fixed_role_model': 'tvae',
    'gradient_penalty_mode': 'NONE',
    'd_model_exp_2': 7,
    'grad_clip': 0.40068617908249937,
    'bias': False,
    'bias_final': True,
    'attn_activation': 'leakyhardsigmoid',
    'inds_init_mode': 'torch',
    'tf_d_inner_exp_2': 8,
    'tf_n_layers_enc': 4,
    'tf_n_head_exp_2': 4,
    'tf_activation': 'leakyhardtanh',
    'tf_activation_final': 'leakyhardsigmoid',
    'tf_num_inds_exp_2': 6,
    'tf_isab_mode': 'separate',
    'ada_d_hid_exp_2': 9,
    'ada_n_layers': 6,
    'ada_activation': 'tanh',
    'ada_activation_final': 'leakyhardtanh',
    'head_d_hid_exp_2': 7,
    'head_n_layers': 6,
    'head_n_head_exp_2': 5,
    'head_activation': 'tanh',
    'head_activation_final': 'identity',
    'patience': 83,
    'dataset_size_low_exp_2': 10,
    'dataset_size_high_exp_2': 11,
    'batch_size_low_exp_2': 2,
    'batch_size_high_exp_2': 2,
    'scheduler_patience': 30
}

#[9.828363181441091e-05, 0.011743317474611104]
BEST_SINGLE = {
    **DEFAULTS,
    'loss_balancer_meta_boolc': True,
    'loss_balancer_beta': 0.770056231662862,
    'loss_balancer_r': 0.9141803569752627,
    'tf_pma_low_exp_2': 1,
    'epochs': 642,
    'lr_mul': 0.18501707951433735,
    'n_warmup_steps': 77.93951314777726,
    'Optim': 'amsgradw',
    'non_role_model_mul': 1.3034359157123085,
    'adapter_loss_fn': 'mire',
    'fixed_role_model': 'lct_gan',
    'gradient_penalty_mode': 'NONE',
    'd_model_exp_2': 7,
    'grad_clip': 0.9841844998040722,
    'bias': True,
    'bias_final': True,
    'attn_activation': 'leakyhardsigmoid',
    'inds_init_mode': 'xavier',
    'tf_d_inner_exp_2': 8,
    'tf_n_layers_enc': 4,
    'tf_n_head_exp_2': 4,
    'tf_activation': 'selu',
    'tf_activation_final': 'leakyhardsigmoid',
    'tf_num_inds_exp_2': 6,
    'tf_isab_mode': 'mini',
    'ada_d_hid_exp_2': 9,
    'ada_n_layers': 6,
    'ada_activation': 'leakyhardsigmoid',
    'ada_activation_final': 'leakyhardsigmoid',
    'head_d_hid_exp_2': 7,
    'head_n_layers': 5,
    'head_n_head_exp_2': 5,
    'head_activation': 'tanh',
    'head_activation_final': 'identity',
    'patience': 100,
    'dataset_size_low_exp_2': 10,
    'dataset_size_high_exp_2': 11,
    'batch_size_low_exp_2': 2,
    'batch_size_high_exp_2': 2,
    'scheduler_patience': 25
}